import { StyleSheet, Platform, StatusBar } from 'react-native';

export const styles = StyleSheet.create({

    safe: {
        flex: 1,
        backgroundColor: '#030712',
    },
    container: { flex: 1 },

    glowBall: {
        position: 'absolute',
        width: 320,
        height: 320,
        borderRadius: 160,
        opacity: 0.25,
    },

    // ── Header ───────────────────────────────────────────────────
    headerGlass: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: 'rgba(255,255,255,0.05)',
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255,255,255,0.12)',
        borderTopWidth: 1,
        borderTopColor: 'rgba(255,255,255,0.08)',
        zIndex: 10,
        marginTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
        elevation: 8,
    },
    navButtonGlass: {
        width: 42,
        height: 42,
        borderRadius: 13,
        backgroundColor: 'rgba(255,255,255,0.08)',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.18)',
        borderTopColor: 'rgba(255,255,255,0.25)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    navButtonText: {
        color: '#4ADE80',
        fontSize: 20,
        fontWeight: '600',
    },
    headerCenter: {
        flex: 1,
        alignItems: 'center',
        gap: 4,
    },
    headerStatus: {
        color: '#FFFFFF',
        fontSize: 13,
        fontWeight: '700',
        letterSpacing: 0.2,
    },
    categoryBadge: {
        backgroundColor: 'rgba(74,222,128,0.12)',
        paddingHorizontal: 10,
        paddingVertical: 3,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: 'rgba(74,222,128,0.3)',
        borderTopColor: 'rgba(74,222,128,0.5)',
    },
    headerCategoryText: {
        color: '#4ADE80',
        fontSize: 11,
        fontWeight: '600',
        letterSpacing: 0.5,
    },

    // ── Lista ─────────────────────────────────────────────────────
    messagesList: {
        paddingHorizontal: 4,
        paddingVertical: 12,
        flexGrow: 1,
        justifyContent: 'flex-end',
    },

    // ── Estado vazio (conectado mas sem mensagens) ────────────────
    emptyGlass: {
        alignSelf: 'center',
        marginTop: 40,
        padding: 24,
        borderRadius: 20,
        backgroundColor: 'rgba(255,255,255,0.04)',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
        borderTopColor: 'rgba(255,255,255,0.18)',
        maxWidth: '75%',
        alignItems: 'center',
    },
    emptyText: {
        color: 'rgba(255,255,255,0.45)',
        fontSize: 13,
        textAlign: 'center',
        lineHeight: 20,
    },

    // ── Overlay de busca de parceiro ──────────────────────────────
    matchingContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingTop: 80,
        paddingHorizontal: 32,
        gap: 12,
    },
    matchingOrb: {
        position: 'absolute',
        top: 40,
        width: 140,
        height: 140,
        borderRadius: 70,
        backgroundColor: 'rgba(74,222,128,0.08)',
        borderWidth: 1,
        borderColor: 'rgba(74,222,128,0.2)',
    },
    matchingEmoji: {
        fontSize: 42,
        marginBottom: 4,
        zIndex: 1,
    },
    matchingTitle: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: '700',
        letterSpacing: 0.2,
        zIndex: 1,
    },
    matchingSubtitle: {
        color: 'rgba(255,255,255,0.4)',
        fontSize: 13,
        textAlign: 'center',
        lineHeight: 20,
        zIndex: 1,
    },
    matchingDots: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 8,
    },

    // ── Área de input ─────────────────────────────────────────────
    inputAreaGlass: {
        paddingHorizontal: 12,
        paddingBottom: Platform.OS === 'ios' ? 28 : 16,
        paddingTop: 10,
        backgroundColor: 'rgba(3,7,18,0.95)',
        borderTopWidth: 1,
        borderTopColor: 'rgba(255,255,255,0.1)',
    },
    inputWrapperGlass: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        backgroundColor: 'rgba(255,255,255,0.07)',
        borderRadius: 28,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.18)',
        borderTopColor: 'rgba(255,255,255,0.3)',
        paddingLeft: 6,
        paddingRight: 6,
        paddingVertical: 6,
        shadowColor: '#4ADE80',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 4,
    },
    input: {
        flex: 1,
        minHeight: 44,
        maxHeight: 110,
        paddingHorizontal: 14,
        paddingVertical: 10,
        color: '#FFFFFF',
        fontSize: 15,
        lineHeight: 20,
        ...Platform.select({ web: { outlineStyle: 'none' } }),
    } as any,
    sendButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: 'rgba(74,222,128,0.9)',
        borderWidth: 1,
        borderColor: 'rgba(74,222,128,1)',
        borderTopColor: 'rgba(200,255,220,0.8)',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#4ADE80',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.45,
        shadowRadius: 8,
        elevation: 5,
    },
    sendButtonDisabled: {
        backgroundColor: 'rgba(255,255,255,0.07)',
        borderColor: 'rgba(255,255,255,0.1)',
        shadowOpacity: 0,
        elevation: 0,
    },
    sendButtonText: {
        color: '#030712',
        fontSize: 16,
        fontWeight: '800',
    },
});
